#!/usr/bin/env bash
# 415-docs session bootstrap -- rendered from bootstrap.sh.tmpl.
# Edit .agents/manifest.yaml and re-render; do not edit this file directly.
set -euo pipefail

AGENTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STATE_DIR="${AGENTS_DIR}/state"
mkdir -p "${STATE_DIR}"
cd "${AGENTS_DIR}/.."   # sentinel paths in the manifest are workspace-relative

log() { printf '[bootstrap] %s\n' "$*"; }
fail() { printf '[bootstrap] ERROR: %s\n' "$*" >&2; exit 1; }

# ---------------------------------------------------------------- apt packages
# Non-interactive frontend for unattended installs [nixcraft-debianfrontend].
export DEBIAN_FRONTEND=noninteractive

APT_PACKAGES=(

  "gnupg"

  "python3-yaml"

  "graphviz"

  "python3-pip"

)

SUDO=""
if [[ "$(id -u)" -ne 0 ]]; then
  command -v sudo >/dev/null || fail "not root and sudo unavailable"
  SUDO="sudo"
fi

missing=()
for spec in "${APT_PACKAGES[@]}"; do
  name="${spec%%=*}"
  # dpkg-query, not command -v, is the authoritative install test [arslan2019]
  if ! dpkg-query -W -f='${Status}' "${name}" 2>/dev/null | grep -q 'install ok installed'; then
    missing+=("${spec}")
  fi
done

if ((${#missing[@]})); then
  log "installing: ${missing[*]}"
  # a single unreachable third-party source must not block bootstrap;
  # the install below is the real gate
  ${SUDO} apt-get update -q || log "warning: apt-get update failed for some sources; attempting install anyway"
  ${SUDO} apt-get install -q -y --no-install-recommends "${missing[@]}"
else
  log "apt dependencies already satisfied"
fi

# ------------------------------------------------------- ephemeral signing key
# Session key in a workspace-local GNUPGHOME [gnupg-unattended]; consumed by
# `git agent-commit` via the AGENT_* environment (see agent-commit skill).
AGENT_GNUPGHOME="${AGENTS_DIR}/gnupg"
AGENT_GIT_NAME="Agent"
AGENT_GIT_EMAIL="ai@blobfish.icu"
AGENT_UID="${AGENT_GIT_NAME} <${AGENT_GIT_EMAIL}>"

live_fpr() {
  # sec validity 'e' = expired, 'r' = revoked: treat both as absent
  gpg --homedir "${AGENT_GNUPGHOME}" --list-secret-keys --with-colons "${AGENT_GIT_EMAIL}" 2>/dev/null \
    | awk -F: '$1=="sec" && $2!="e" && $2!="r" {take=1; next}
               take && $1=="fpr" {print $10; exit}'
}

fpr="$(live_fpr || true)"
if [[ -z "${fpr}" ]]; then
  log "generating ephemeral agent key for ${AGENT_UID}"
  rm -rf "${AGENT_GNUPGHOME}"
  mkdir -p "${AGENT_GNUPGHOME}" && chmod 700 "${AGENT_GNUPGHOME}"
  # Unattended, passphrase-less by design: the key is short-lived and local,
  # a bookkeeping marker rather than a long-term credential [gnupg-keymgmt]
  gpg --homedir "${AGENT_GNUPGHOME}" --batch --pinentry-mode loopback --passphrase '' \
      --quick-generate-key "${AGENT_UID}" ed25519 sign "1w"
  fpr="$(live_fpr)"
  [[ -n "${fpr}" ]] || fail "key generation produced no usable secret key"
else
  log "reusing live agent key ${fpr}"
fi

gpg --homedir "${AGENT_GNUPGHOME}" --armor --export "${fpr}" > "${AGENTS_DIR}/agent-pubkey.asc"
expiry_epoch="$(gpg --homedir "${AGENT_GNUPGHOME}" --list-keys --with-colons "${fpr}" \
  | awk -F: '$1=="pub" {print $7; exit}')"
log "key ${fpr} expires $(date -u -d "@${expiry_epoch}" '+%Y-%m-%d' 2>/dev/null || echo 'never')"
log "public key exported to ${AGENTS_DIR}/agent-pubkey.asc -- provide it to the user for forge registration [github-gpg]"

cat > "${AGENTS_DIR}/agent-env.sh" <<EOF
export AGENT_GIT_NAME="${AGENT_GIT_NAME}"
export AGENT_GIT_EMAIL="${AGENT_GIT_EMAIL}"
export AGENT_SIGNING_KEY="${fpr}"
export AGENT_GNUPGHOME="${AGENT_GNUPGHOME}"
EOF
chmod 600 "${AGENTS_DIR}/agent-env.sh"
log "agent identity ready; source ${AGENTS_DIR}/agent-env.sh"

# ------------------------------------------------------------------ baselines
# Recorded desired-vs-actual reference points for healthcheck.sh; drift is a
# divergence from a recorded baseline, not from guesswork [ibm-drift]
sha256sum "${AGENTS_DIR}/manifest.yaml" | awk '{print $1}' > "${STATE_DIR}/manifest.sha256"

: > "${STATE_DIR}/dpkg-versions.txt"
for spec in "${APT_PACKAGES[@]}"; do
  dpkg-query -W -f='${Package} ${Version}\n' "${spec%%=*}" >> "${STATE_DIR}/dpkg-versions.txt"
done

{

  sha256sum ".agents/bootstrap.sh.tmpl"

  sha256sum ".agents/check.sh.tmpl"

  sha256sum ".agents/healthcheck.sh.tmpl"

  sha256sum ".agents/render.py"

} > "${STATE_DIR}/sentinels.sha256"

log "bootstrap complete"
