#!/usr/bin/env bash
# 415-docs dependency validation -- rendered from check.sh.tmpl.
# Edit .agents/manifest.yaml and re-render; do not edit this file directly.
set -euo pipefail

AGENTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
failures=0
flag() { printf '[check] FAIL: %s\n' "$*" >&2; failures=$((failures + 1)); }
ok() { printf '[check] ok: %s\n' "$*"; }

# dpkg state proves the package installed; a runnable command on PATH proves
# it usable -- either alone gives false confidence [arslan2019]

if dpkg-query -W -f='${Status}' "gnupg" 2>/dev/null | grep -q 'install ok installed'; then
  ok "package gnupg"
else
  flag "package gnupg not installed"
fi

if dpkg-query -W -f='${Status}' "python3-yaml" 2>/dev/null | grep -q 'install ok installed'; then
  ok "package python3-yaml"
else
  flag "package python3-yaml not installed"
fi

if dpkg-query -W -f='${Status}' "graphviz" 2>/dev/null | grep -q 'install ok installed'; then
  ok "package graphviz"
else
  flag "package graphviz not installed"
fi

if dpkg-query -W -f='${Status}' "python3-pip" 2>/dev/null | grep -q 'install ok installed'; then
  ok "package python3-pip"
else
  flag "package python3-pip not installed"
fi



if command -v "gpg" >/dev/null; then
  ok "command gpg ($("gpg" --version 2>&1 | head -n 1))"
else
  flag "command gpg missing from PATH (expected via gnupg)"
fi

if command -v "dot" >/dev/null; then
  ok "command dot ($("dot" -V 2>&1 | head -n 1))"
else
  flag "command dot missing from PATH (expected via graphviz)"
fi

if command -v "pip3" >/dev/null; then
  ok "command pip3 ($("pip3" --version 2>&1 | head -n 1))"
else
  flag "command pip3 missing from PATH (expected via python3-pip)"
fi


# Agent identity produced by bootstrap.sh and required by git agent-commit
if [[ -r "${AGENTS_DIR}/agent-env.sh" ]]; then
  # shellcheck source=/dev/null
  source "${AGENTS_DIR}/agent-env.sh"
  if gpg --homedir "${AGENT_GNUPGHOME}" --list-secret-keys --with-colons "${AGENT_SIGNING_KEY}" 2>/dev/null \
       | awk -F: '$1=="sec" && $2!="e" && $2!="r" {found=1} END {exit !found}'; then
    ok "agent signing key ${AGENT_SIGNING_KEY}"
  else
    flag "agent signing key ${AGENT_SIGNING_KEY} missing, expired, or revoked"
  fi
else
  flag "agent-env.sh missing; run .agents/bootstrap.sh"
fi

if ((failures)); then
  printf '[check] %d failure(s); run .agents/bootstrap.sh or fix the manifest\n' "${failures}" >&2
  exit 1
fi
printf '[check] all dependencies validated\n'
