#!/usr/bin/env bash
# 415-docs environment healthcheck -- rendered from healthcheck.sh.tmpl.
# Edit .agents/manifest.yaml and re-render; do not edit this file directly.
#
# Compares the live environment against the baselines bootstrap.sh recorded,
# the IaC drift-detection pattern: desired state is code, drift is divergence
# from it [hashicorp-drift]. Verdict contract (machine-readable last line):
#   HEALTHCHECK: ok       exit 0   environment matches baselines
#   HEALTHCHECK: drift    exit 1   recoverable divergence; re-render/re-bootstrap
#   HEALTHCHECK: corrupt  exit 2   integrity violation; stop and tell the user
set -uo pipefail

AGENTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STATE_DIR="${AGENTS_DIR}/state"
cd "${AGENTS_DIR}/.." || { echo "HEALTHCHECK: corrupt"; exit 2; }

verdict=0
note() { printf '[healthcheck] %s\n' "$*"; }
drift() { note "DRIFT: $*"; ((verdict < 1)) && verdict=1; }
corrupt() { note "CORRUPT: $*"; verdict=2; }

if [[ ! -d "${STATE_DIR}" ]]; then
  corrupt "no recorded baselines; .agents/bootstrap.sh has never completed here"
fi

# Manifest changed since the scripts were rendered => scripts are stale
if [[ -f "${STATE_DIR}/manifest.sha256" ]]; then
  current="$(sha256sum "${AGENTS_DIR}/manifest.yaml" | awk '{print $1}')"
  recorded="$(cat "${STATE_DIR}/manifest.sha256")"
  [[ "${current}" == "${recorded}" ]] \
    || drift "manifest.yaml changed after last bootstrap; re-render *.tmpl and re-run bootstrap"
fi

# Package set drift: removed packages are corruption, version churn is drift

if ! dpkg-query -W -f='${Status}' "gnupg" 2>/dev/null | grep -q 'install ok installed'; then
  corrupt "required package gnupg is no longer installed"
fi

if ! dpkg-query -W -f='${Status}' "python3-yaml" 2>/dev/null | grep -q 'install ok installed'; then
  corrupt "required package python3-yaml is no longer installed"
fi

if ! dpkg-query -W -f='${Status}' "graphviz" 2>/dev/null | grep -q 'install ok installed'; then
  corrupt "required package graphviz is no longer installed"
fi

if ! dpkg-query -W -f='${Status}' "python3-pip" 2>/dev/null | grep -q 'install ok installed'; then
  corrupt "required package python3-pip is no longer installed"
fi

if [[ -f "${STATE_DIR}/dpkg-versions.txt" ]]; then
  while read -r name recorded_ver; do
    live_ver="$(dpkg-query -W -f='${Version}' "${name}" 2>/dev/null || true)"
    [[ "${live_ver}" == "${recorded_ver}" ]] \
      || drift "package ${name} moved ${recorded_ver} -> ${live_ver:-<absent>} since bootstrap"
  done < "${STATE_DIR}/dpkg-versions.txt"
fi

# Sentinel files: silent mutation of the environment's own machinery
if [[ -f "${STATE_DIR}/sentinels.sha256" ]]; then
  if ! sha256sum --check --quiet "${STATE_DIR}/sentinels.sha256" 2>/dev/null; then
    corrupt "sentinel file checksum mismatch (see: sha256sum --check ${STATE_DIR}/sentinels.sha256)"
  fi
fi

# Workspace skill copies still present and non-empty


# Agent key: expiry is the designed staleness alarm
if [[ -r "${AGENTS_DIR}/agent-env.sh" ]]; then
  # shellcheck source=/dev/null
  source "${AGENTS_DIR}/agent-env.sh"
  gpg --homedir "${AGENT_GNUPGHOME}" --list-secret-keys --with-colons "${AGENT_SIGNING_KEY}" 2>/dev/null \
    | awk -F: '$1=="sec" && $2!="e" && $2!="r" {found=1} END {exit !found}' \
    || drift "agent signing key unusable (likely expired); re-run bootstrap to mint a fresh one"
else
  drift "agent-env.sh missing; re-run bootstrap"
fi

# Project-specific indicators from the manifest

if ! bash -c 'git rev-parse --is-inside-work-tree' >/dev/null 2>&1; then
  drift "extra check failed: inside the 415-docs repo"
fi

if ! bash -c 'pip3 show sphinx 2>/dev/null | grep -q 6.2.1' >/dev/null 2>&1; then
  drift "extra check failed: sphinx importable at pinned version"
fi

if ! bash -c 'command -v git-agent-commit || test -x "$HOME/.local/bin/git-agent-commit"' >/dev/null 2>&1; then
  drift "extra check failed: agent-commit wrapper installed"
fi


case "${verdict}" in
  0) echo "HEALTHCHECK: ok" ;;
  1) echo "HEALTHCHECK: drift" ;;
  *) echo "HEALTHCHECK: corrupt" ;;
esac
exit "${verdict}"
