name: Link Checker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  linkcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check links with lychee
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress --exclude-path base/index.html --exclude-all-private '**/*.md' '**/*.rst' '**/*.html' '**/*.tex'
          fail: true
